language: node_js
dist: trusty
node_js:
  - "14"
script:
  - make lint
before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      openssl aes-256-cbc -K $encrypted_a0cef55ae934_key -iv $encrypted_a0cef55ae934_iv -in burlesco-rsa-key.pem.enc -out burlesco-rsa-key.pem -d
      make build || travis_terminate 1;
      bash scripts/gen-gh-pages.sh || travis_terminate 1;
    fi
deploy:
  - provider: releases
    skip_cleanup: true
    file:
      - dist/chromium/burlesco-chromium.crx
      - dist/chromium/burlesco-chromium.zip
      - dist/firefox/burlesco-firefox.xpi
      - dist/firefox/burlesco-firefox.zip
    on:
      branch: master
      tags: true
  - provider: pages
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    repo: burlesco/burlesco-update
    target_branch: master
    local_dir: gh-pages
    on:
      branch: master
      tags: true
