name: Burlesco Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master, test ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: lint
        run: |
          make lint
      - name: build
        run: |
          make build
      - run: echo "This job's status is ${{ job.status }}."
